- name: Set up Podman containers for Nginx and Certbot
  block:

    - name: Pull nginx image
      containers.podman.podman_image:
        name: nginx:latest
        state: present

    - name: Pull certbot image
      containers.podman.podman_image:
        name: docker.io/certbot/certbot:nightly
        state: present

    - name: Create persistent volumes for certbot and nginx
      containers.podman.podman_volume:
        name: "{{ item }}"
        state: present
      loop:
        - certbot_certs
        - certbot_www

    - name: Ensure the directory /etc/nginx exists
      ansible.builtin.file:
        path: /etc/nginx
        state: directory

    - name: Copy Nginx configuration file
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'

    
    - name: Run nginx container
      containers.podman.podman_container:
        name: nginx
        image: nginx:latest
        state: started
        restart: yes
        network: web_net
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - certbot_certs:/etc/letsencrypt:z
          - certbot_www:/var/www/certbot:z
          - /etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:Z

    - name: Get initial certs using certbot standalone
      containers.podman.podman_container:
        name: certbot
        image: docker.io/certbot/certbot:nightly
        command: "certonly --webroot --webroot-path=/var/www/certbot --non-interactive --agree-tos -m grps.hq@gmail.com -d www.appsecacademy.tech -d appsecacademy.tech"
        detach: false
        network: web_net
        volumes:
          - certbot_certs:/etc/letsencrypt
          - certbot_www:/var/www/certbot

    - name: Create certbot renewal timer
      ansible.builtin.cron:
        name: "Certbot renewal"
        minute: "0"
        hour: "0"
        day: "1"
        month: "*"
        job: "podman run --rm --name certbot_renew --network=web_net -v cert"
    
    - name: Copy new Nginx configuration file
      template:
        src: nginx.conf.j2.bak
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'

    - name: Restart Nginx container
      containers.podman.podman_container:
        name: nginx
        image: nginx:latest
        state: started
        restart: yes
        network: web_net
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - certbot_certs:/etc/letsencrypt:z
          - certbot_www:/var/www/certbot:z
          - /etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:Z
  vars:
    registry_username: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65323333373633636131633263613464643464623135313965376231323738353730653937303236
          6635366465316430663236323362393232613237383335650a646636373330373935666139356137
          66336563663630386435326433396434633230616132356537366564653065643966333963373765
          3166303435653233650a333438376636313037623336356261353139643033373861316164613363
          3965
    registry_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32346363383763376338346134373666363239316331656534316262613035383531633834646466
          6431623338346161656136646364616135313334656163390a653935303862666462353830643734
          37356136383736363935623365373639343862373733636264616666653131306237356630353263
          3735663431343964610a346661626462666631396634663463373238663934666334356239646531
          3432
